<div class="container">
    <div id="page"><link href="inc/footable.bootstrap.min.css" rel="stylesheet">
<script src="inc/footable.min.js"></script>
<script>
jQuery(function($){
	$('.table').footable();
});
</script>

<br>
<center>
<p> A continuación presentamos unos valores aproximados de rendimiento ( Hash) en minar BitcoinN según diferentes configuraciones de hardware. <br>Puedes ayudar compartiendo tus resultados enviando un email a (d e v @ b i t c o i n n. b i z) </p>
</center>
<hr>

<table class="table footable footable-1 footable-filtering footable-filtering-right breakpoint-lg" data-filtering="true" data-sorting="true" style="display: table;">
	<thead> <!-- <tr class="footable-filtering"><th colspan="6"><form class="form-inline"><div class="form-group footable-filtering-search"><label class="sr-only">Search</label><div class="input-group"><input class="form-control" placeholder="Search" type="text"><div class="input-group-btn"><button type="button" class="btn btn-primary"><span class="fooicon fooicon-search"></span></button><button type="button" class="btn btn-default dropdown-toggle"><span class="caret"></span></button><ul class="dropdown-menu dropdown-menu-right"><li><a class="checkbox"><label><input checked="checked" type="checkbox">Software</label></a></li><li><a class="checkbox"><label><input checked="checked" type="checkbox">Tipus</label></a></li><li><a class="checkbox"><label><input checked="checked" type="checkbox">Model / Referencia</label></a></li><li><a class="checkbox"><label><input checked="checked" type="checkbox"> Hash</label></a></li><li><a class="checkbox"><label><input checked="checked" type="checkbox">Consum aprox. (W)</label></a></li><li><a class="checkbox"><label><input checked="checked" type="checkbox">Comentarios</label></a></li></ul></div></div></div></form></th></tr> -->
	<tr class="footable-header">

	<th class="footable-sortable footable-first-visible footable-asc" style="display: table-cell;">Software<span class="fooicon fooicon-sort-asc"></span></th><th class="footable-sortable" style="display: table-cell;">Tipo<span class="fooicon fooicon-sort"></span></th><th class="footable-sortable" style="display: table-cell;">Model / Referencia<span class="fooicon fooicon-sort"></span></th><th data-type="number" data-sorted="true" data-direction="DESC" class="footable-sortable" style="display: table-cell;"> Hash<span class="fooicon fooicon-sort"></span></th><th data-type="number" class="footable-sortable" style="display: table-cell;">Consum aprox. (W)<span class="fooicon fooicon-sort"></span></th><th data-sortable="false" style="display: table-cell;" class="footable-last-visible">Comentarios</th></tr>
	</thead>
	<tbody>



	<tr>

        <td style="display: table-cell;" class="footable-first-visible">ccminer 2.2.3 x64</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">MSI GTX1080Ti Gaming X</td><td style="display: table-cell;">785</td><td style="display: table-cell;">117</td><td style="display: table-cell;" class="footable-last-visible">Core clk +100, Mem clk +80, PL 85%</td></tr><tr>
	<td style="display: table-cell;" class="footable-first-visible">Claymore CryptoNote CPU 3.5</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">i5-7200U 2.5Ghz (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">47</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore CryptoNote CPU 3.5</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">AMD Turion II Neo N40L Dual-Core 1.5</td><td style="display: table-cell;">10</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore CryptoNote CPU 3.5</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">i7-860 2.8</td><td style="display: table-cell;">14</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore GPU Miner v10.2</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">R7 370</td><td style="display: table-cell;">450</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">OverClock (1150 / 1550)</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore GPU Miner v11.2</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">RX 570 NITRO+ OC 4GB</td><td style="display: table-cell;">780</td><td style="display: table-cell;">160</td><td style="display: table-cell;" class="footable-last-visible">Win10 - modbios + OC 1200/2035</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore GPU Miner v11.2</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">RX 560</td><td style="display: table-cell;">440</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">modbios</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore GPU Miner v9.7</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">GTX 1050 Ti 4Gb</td><td style="display: table-cell;">306</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore GPU Miner v9.7</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">ASUS R9 270x</td><td style="display: table-cell;">470</td><td style="display: table-cell;">160</td><td style="display: table-cell;" class="footable-last-visible">OverClock (factory clock: 410 H/S)</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore GPU Miner v9.7</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">MSI R9 270</td><td style="display: table-cell;">470</td><td style="display: table-cell;">160</td><td style="display: table-cell;" class="footable-last-visible">OverClock (factory clock: 410 H/S)</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore GPU Miner v9.7</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">MSI Radeon RX480 4Gb</td><td style="display: table-cell;">630</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">Claymore GPU Miner v9.7</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">MSI Radeon RX570 4Gb</td><td style="display: table-cell;">590</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">cpuminer-multi-rel1.3.1-x64</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">Intel pentium G2030</td><td style="display: table-cell;">25</td><td style="display: table-cell;">30</td><td style="display: table-cell;" class="footable-last-visible">t1</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">cpuminer-multi-rel1.3.1-x64</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">i3-6100 (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">79</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">Arch Linux</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">SG Miner 5.5.5-gm</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">4GB RX 560 MSI AERO ITX OC</td><td style="display: table-cell;">330</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">Ubuntu 16.04</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">SG Miner 5.5.5-gm</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">2GB RX 560 ASUS RADEON OC</td><td style="display: table-cell;">300</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">Ubuntu 16.04</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-Stak</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">Intel Core i7-6800k (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">350</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">threads(0,2,4,6,8,10) - 41º</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-Stak</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">Intel Core i7-6800k (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">372</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">OC Asus automatic - 43,5º</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-Stak</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">AMD Ryzen 7 1700 (AES CPU)</td><td style="display: table-cell;">480</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">Threads 1,3,5,7,9,11,13,15</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-Stak</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">Sapphire RX570 ITX Pulse</td><td style="display: table-cell;">480</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-Stak-CPU</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">i5-7200U 2.5Ghz (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">47</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-Stak-CPU</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">i7-6700 (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">193</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-Stak-CPU</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">AMD Ryzen 5 1600 (AES CPU)</td><td style="display: table-cell;">412</td><td style="display: table-cell;">65</td><td style="display: table-cell;" class="footable-last-visible">threads(1,3,5,7,9,11)</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-Stak-CPU</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">i3-6100 (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">48</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">Arch Linux</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">XMR-STAK-NVIDIa-LINUX</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">GTX 1060 EVGA</td><td style="display: table-cell;">455</td><td style="display: table-cell;">60</td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">xmrig-2.4.2</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">i5-7300HQ (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">183</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">t3 (win7)</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">xmrig-2.4.2</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">i5-7300HQ (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">150</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">t3 (Ubuntu 16.04)</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">xmrig-2.4.2</td><td style="display: table-cell;">GPU</td><td style="display: table-cell;">GTX 1050 4Gb</td><td style="display: table-cell;">287</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">xmrig-2.4.3-gcc-win64</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">Intel pentium G4400 (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">70</td><td style="display: table-cell;">30</td><td style="display: table-cell;" class="footable-last-visible">Huge Page enabled, t1 (one core)</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">xmrig-2.4.3-gcc-win64</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">AMD FX-8350 (AES CPU)</td><td style="display: table-cell;">350</td><td style="display: table-cell;">120</td><td style="display: table-cell;" class="footable-last-visible">Huge Page enabled, t6</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">xmrig-2.4.3-gcc-win64</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">Intel Xeon E3 1220 v5 (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">260</td><td style="display: table-cell;">80</td><td style="display: table-cell;" class="footable-last-visible">Huge Page enabled, t4</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">xmrig-2.4.3-gcc-win64</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">Intel Core i5-7200U 2.5GHz (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">50</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible">t4 (t0/t2 40H/s)</td></tr><tr>
        <td style="display: table-cell;" class="footable-first-visible">xmrig-2.4.3-gcc-win64</td><td style="display: table-cell;">CPU</td><td style="display: table-cell;">Intel Core i7-7Y75 2.5GHz (<a href="https://ark.intel.com/es-es/Search/FeatureFilter?productType=processors&amp;AESTech=true" target="blank_">AES CPU</a>)</td><td style="display: table-cell;">53</td><td style="display: table-cell;"></td><td style="display: table-cell;" class="footable-last-visible"></td></tr></tbody>

</table>

</div>

